name: budget_balanced
description: A personal budgeting app
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  go_router: ^13.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  path_provider: ^2.0.14
  collection: ^1.17.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
